# Generated by Django 2.1.7 on 2019-03-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_auto_20190301_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 1, 18, 26, 25, 474904)),
        ),
    ]
