# Generated by Django 2.1.7 on 2019-03-01 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20190302_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 2, 26, 24, 816583)),
        ),
    ]
