# Generated by Django 2.1.7 on 2019-03-01 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20190302_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 3, 1, 14, 747122)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
