# Generated by Django 2.1.7 on 2019-03-01 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20190302_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 3, 10, 50, 554881)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
