# Generated by Django 2.1.7 on 2019-03-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_auto_20190301_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 1, 18, 26, 25, 447671)),
        ),
    ]
