# Generated by Django 2.1.7 on 2019-03-01 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_auto_20190301_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 1, 8, 45, 998751)),
        ),
    ]
