# Generated by Django 2.1.7 on 2019-03-01 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0013_auto_20190302_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 3, 9, 39, 590162)),
        ),
    ]
