# Generated by Django 2.1.7 on 2019-05-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0015_auto_20190302_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 3, 33, 17, 451891)),
        ),
    ]
