# Generated by Django 2.1.7 on 2019-03-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20190301_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 1, 18, 26, 25, 472033)),
        ),
    ]
